services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass1234 # Naturally in a real environment you'd want something better than this
      POSTGRES_DB: rocket-blogger
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
  web:
    depends_on:
      db:
        condition: service_healthy
    build: .
    ports:
      - 8080:8080/tcp
    environment:
      DATABASE_URL: postgres://postgres:pass1234@db:5432/rocket-blogger
      ROCKET_DATABASES: "{rocket-blogger={url=\"$DATABASE_URL\"}}"
